#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  SELECT 'CREATE ROLE ${DISCLOSURE_DB_USER} LOGIN PASSWORD ''${DISCLOSURE_DB_PASSWORD}''' WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${DISCLOSURE_DB_USER}')\gexec
  SELECT 'CREATE DATABASE ${DISCLOSURE_DB_NAME} OWNER ${DISCLOSURE_DB_USER}' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${DISCLOSURE_DB_NAME}')\gexec
  SELECT 'CREATE ROLE ${CHAT_DB_USER} LOGIN PASSWORD ''${CHAT_DB_PASSWORD}''' WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${CHAT_DB_USER}')\gexec
  SELECT 'CREATE DATABASE ${CHAT_DB_NAME} OWNER ${CHAT_DB_USER}' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${CHAT_DB_NAME}')\gexec
  SELECT 'CREATE ROLE ${AEGRA_DB_USER} LOGIN PASSWORD ''${AEGRA_DB_PASSWORD}''' WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${AEGRA_DB_USER}')\gexec
  SELECT 'CREATE DATABASE ${AEGRA_DB_NAME} OWNER ${AEGRA_DB_USER}' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${AEGRA_DB_NAME}')\gexec
EOSQL
